---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-external-dns
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    kubernetes.io/metadata.name: external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns-installation
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: external-dns
      version: '6.31.2'
      sourceRef:
        kind: HelmRepository
        name: helm-repo-external-dns
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    provider: azure
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: ${dnsManagementClientId:=notProvided}
      labels:
        azure.workload.identity/use: "true"
    azure:
      useManagedIdentityExtension: true
      resourceGroup: ${dnsManagementAzureResourceGroup:=notProvided}
      tenantId: ${azureTenantId:=notProvided}
      subscriptionId: ${azureSubscriptionId:=notProvided}
      userAssignedIdentityID: ${dnsManagementClientId:=notProvided}
