---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-external-dns
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  secretRef:
    name: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    kubernetes.io/metadata.name: external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns-installation
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: external-dns
      version: '6.26.*'
      sourceRef:
        kind: HelmRepository
        name: helm-repo-external-dns
  releaseName: external-dns
  targetNamespace: external-dns
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
      optional: true

