---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.jetstack.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    kubernetes.io/metadata.name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager-installation
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: cert-manager
      version: 'v1.13.3'
      sourceRef:
        kind: HelmRepository
        name: helm-repo-cert-manager
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    installCRDs: true
    startupapicheck:
      enabled: false
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: ${dnsManagementClientId:=notProvided}
      labels:
        azure.workload.identity/use: "true"
    podLabels:
      azure.workload.identity/use: "true"
