---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-external-dns
  namespace: external-dns
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: ${dns-management-client-id:=notFound}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-values
data:
  values.yaml: |
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: ${dns-management-client-id:=notProvided}
      labels:
        azure.workload.identity/use: "true"
    azure:
      cloud: azure
      resourceGroup: ${dns-management-azure-resource-group:=notProvided}
      tenantId: ${azure-tenant-id:=notProvided}
      subscriptionId: ${azure-subscription-id:=notProvided}
      userAssignedIdentityID: ${dns-management-client-id:=notProvided}
      
