---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-traefik
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://traefik.github.io/charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    kubernetes.io/metadata.name: ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik-installation
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: traefik
      version: '26.0.0'
      sourceRef:
        kind: HelmRepository
        name: helm-repo-traefik
  releaseName: traefik
  targetNamespace: ingress
  values:
    # traefik values
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: 'traefik'
                app.kubernetes.io/instance: 'traefik-ingress'
            topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - 'traefik'
              topologyKey: "topology.kubernetes.io/zone"
    globalArguments:
      - "--global.checknewversion"
      - "--serverstransport.maxidleconnsperhost=1000"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=:443"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
