---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-kubernetes-replicator
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://helm.mittwald.de
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-replicator
  labels:
    kubernetes.io/metadata.name: kubernetes-replicator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubernetes-replicator-installation
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: kubernetes-replicator
      version: '2.9.2'
      sourceRef:
        kind: HelmRepository
        name: helm-repo-kubernetes-replicator
  releaseName: kubernetes-replicator
  targetNamespace: kubernetes-replicator
  values: {}

