apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://capsule.k01.labs.g-c.dev
    name: capsule-api-server
contexts:
  - context:
      cluster: capsule-api-server
      user: tenant-user
    name: capsule-context
current-context: capsule-context
users:
  - name: tenant-user
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - --login
          - azurecli
          - --server-id
          - 6dae42f8-4368-4678-94ff-3960e28e3630 # <-- well-known server-id for Azure AKS service
        command: kubelogin