---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-capsule
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://clastix.github.io/charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: capsule
  labels:
    kubernetes.io/metadata.name: capsule
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capsule-installation
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: capsule
      version: '0.4.6'
      sourceRef:
        kind: HelmRepository
        name: helm-repo-capsule
  releaseName: capsule
  targetNamespace: capsule
  values:
    options:
      forceTenantPrefix: true
      generateCertificates: false
      capsuleUserGroups:
        # https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/ac798281-c2d0-4114-8c41-d0cc0f830bb6/menuId/
        - "ac798281-c2d0-4114-8c41-d0cc0f830bb6"

