apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  annotations:
    meta.g-c.dev/slack-channel: team-alice-notifications
    meta.g-c.dev/tenant-name: team-alice-tenant01
    meta.g-c.dev/tenant-owner: team-alice
    # team alice group uuid
    meta.g-c.dev/tenant-owner-uuid: "05e27ec5-27f7-4bf6-b269-f4f53cf31f34"
  labels:
    tenant-owner: team-alice
    tenant-cost-center: "c12345"
  name: team-alice-tenant01
spec:
  ingressOptions:
    allowedClasses:
      allowed:
        - traefik
      matchLabels:
        app.kubernetes.io/name: traefik
    allowedHostnames:
      allowedRegex: ^.${clusterFQDN:=notProvided}$
    hostnameCollisionScope: Cluster
  limitRanges:
    items:
      - limits:
          - default:
              cpu: 500m
              memory: 128Mi
            defaultRequest:
              cpu: 500m
              memory: 128Mi
            type: Container
  namespaceOptions:
    quota: 3
    additionalMetadata:
      annotations:
        meta.g-c.dev/slack-channel: team-alice-notifications
        meta.g-c.dev/tenant-name: team-alice-tenant01
        meta.g-c.dev/tenant-owner: team-alice
      labels:
        tenant-owner: team-alice
        tenant-cost-center: "c12345"
  networkPolicies:
    items:
      - ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: ingress
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: monitoring
        podSelector: { }
        policyTypes:
          - Ingress
  owners:
    - clusterRoles:
        - admin
        - capsule-namespace-deleter
      kind: Group
      name:
        # team alice group uuid
        - "05e27ec5-27f7-4bf6-b269-f4f53cf31f34"
      proxySettings:
        - kind: StorageClasses
          operations:
            - List
        - kind: Nodes
          operations:
            - List
        - kind: IngressClasses
          operations:
            - List
  resourceQuotas:
    items:
      - hard:
          limits.cpu: 2000m
          limits.memory: 4000Mi
          requests.cpu: 1000m
          requests.memory: 2000Mi
    scope: Tenant
  serviceOptions:
    additionalMetadata:
      annotations:
        meta.g-c.dev/slack-channel: team-alice-notifications
        meta.g-c.dev/tenant-name: team-alice-tenant01
        meta.g-c.dev/tenant-owner: team-alice
      labels:
        tenant-owner: team-alice
        tenant-cost-center: "c12345"
    allowedServices:
      externalName: true
      loadBalancer: false
      nodePort: true
  storageClasses:
    matchLabels:
      kubernetes.io/cluster-service: "true"
